# Generated by Django 5.0.4 on 2024-05-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T_K_L', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='transaction_name',
            new_name='transaction',
        ),
        migrations.AddField(
            model_name='details',
            name='Total_Transfer_Amount',
            field=models.CharField(default='Current Total transfer amount', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='current_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='details',
            name='recipent_country',
            field=models.CharField(default='Current country name', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='recipent_name',
            field=models.CharField(default='Current Recipients name', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='senders_bank',
            field=models.CharField(default='Current senders bank name', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='senders_country',
            field=models.CharField(default='Current senders country name', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='senders_name',
            field=models.CharField(default='Current senders name', max_length=20),
        ),
        migrations.AddField(
            model_name='details',
            name='status_update',
            field=models.CharField(default='In progress', max_length=20),
        ),
    ]
