# Generated by Django 5.0.4 on 2024-05-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T_K_L', '0003_details_recipients_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='image',
            field=models.ImageField(default='image_field', upload_to='images/'),
        ),
    ]
