# Generated by Django 5.0.4 on 2024-05-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T_K_L', '0005_alter_details_recipients_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='recipent_bank',
            field=models.CharField(default='Current recipient bank name', max_length=200),
        ),
    ]
